{
 "title": "SLEdge",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "CONIX /fib",
   "type": "stat",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "conix_fib_total_requests:", "legendFormat": "Requests" },
    { "expr": "conix_fib_total_2XX:", "legendFormat": "2XX Responses" },
    { "expr": "conix_fib_total_4XX:", "legendFormat": "4XX Responses" },
    { "expr": "conix_fib_total_5XX:", "legendFormat": "5XX Responses" }
   ]
  },
  {
   "title": "Requests Per Second",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 9, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "rate(total_requests:[$__rate_interval])",
     "legendFormat": "__auto"
    },
    {}
   ]
  },
  {
   "title": "Total Sandboxes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 5 },
   "targets": [
    { "expr": "total_sandboxes:", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "SLEdge Process Accounting",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 4, "x": 12, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(os_proc_guest_time:[$__rate_interval])",
     "legendFormat": "Guest"
    },
    {
     "expr": "rate(os_proc_sys_time:[$__rate_interval])",
     "legendFormat": "Sys"
    },
    {
     "expr": "rate(os_proc_user_time:[$__rate_interval])",
     "legendFormat": "User"
    }
   ]
  },
  {
   "title": "Total 5XX Responses",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 16, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "total_5XX:", "legendFormat": "__auto" }
   ]
  }
 ]
}